### ISSUE TITLE
Métricas

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2013#12]
¿Alguien más piensa que deberíamos recoger algún tipo de métricas o estadísticas sobre las visitas a la página? Al menos para ir registrando desde donde llega la gente, ahora que de momento no hay más contenido.

**Comment by yamila-moreno** [comment]
Google analytics?

2013/3/14 Juan Luis Cano Rodríguez notifications@github.com

> ¿Alguien más piensa que deberíamos recoger algún tipo de métricas o
> estadísticas sobre las visitas a la página? Al menos para ir registrando
> desde donde llega la gente, ahora que de momento no hay más contenido.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python-spain/pycones-web/issues/12
> .

## 

Yamila  Moreno Suárez
http://dendarii.wordpress.com
http://moduslaborandi.net

**Comment by astrojuanlu** [comment]
En eso estaba pensando yo. Yo tengo cuenta ahí, pero obviamente invitaría como mínimo a todos los que estamos participando en la web para verlas.

**Comment by yamila-moreno** [comment]
+100

2013/3/14 Juan Luis Cano Rodríguez notifications@github.com

> En eso estaba pensando yo. Yo tengo cuenta ahí, pero obviamente invitaría
> como mínimo a todos los que estamos participando en la web para verlas.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python-spain/pycones-web/issues/12#issuecomment-14904554
> .

## 

Yamila  Moreno Suárez
http://dendarii.wordpress.com
http://moduslaborandi.net

**Comment by ghost** [comment]
:+1:

**Comment by niwinz** [comment]
+1

**Comment by achamorro-dev** [comment]
+1

**Comment by astrojuanlu** [comment]
Ya está recibiendo datos :D A falta de que Jesús Cea me diga (o me recuerde) el alias de correo y que todos podamos ver los datos.
