### ISSUE TITLE
Unificar entornos de producción y desarrollo

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2013#14]
Ahora mismo estamos guardando algunos datos sensibles relativos al servidor de correo en settings.py. Esto significa que para proteger esos datos del público tenemos que hacer diverger la historia para el entorno de producción, y creo que puede traer problemas. He pensado que podríamos usar variables de entorno para ello; en Heroku es muy fácil, y si no me equivoco es una solución aceptada y utilizada. Otra sería usar la base de datos.

Pensaba hacerlo yo ahora, pero necesito especialmente revisión porque como me cargue algo ahora puede ser un poco problemático.

**Comment by niwinz** [comment]
seria mas que evidente la necesidad de quitar datos de produccion del control de versiones. Variables de entorno es una elegante solucion.

**Comment by ghost** [comment]
Puedes usar `os.getenv` para acceder a las variables de entorno, y opcionalmente dar un valor por
defecto en caso de que no se encuentre:

``` python
os.getenv('EMAIL_HOST', 'smtp.gmail.com')
```

También con `os.environ.get`. La información de producción no debería estar en el repositorio,
especialmente la `SECRET_KEY`.

**Comment by niwinz** [comment]
La secret key puede estar en el repo sin problemas ya que sirve perfectamente para desarrollo, solo que en produccion hay que sobreescribirla.

**Comment by astrojuanlu** [comment]
@alejandrogomez Sí, por lo visto `os.getenv` y `os.environ.get` son exactamente lo mismo.
@niwibe Entonces se puede dejar como default la secret key de desarollo y en producción se importa del diccionario de las variables de entorno, ¿no?

**Comment by niwinz** [comment]
Al final del settings.py se podria añadir algo asi:

```
if "SECRET_KEY" in os.environ:
    SECRET_KEY = os.environ["SECRET_KEY"]
```

Y de esta manera no es nada intrusivo para el desarrollador.

**Comment by ghost** [comment]
:+1: a la solución de @niwibe.

**Comment by astrojuanlu** [comment]
Pero entonces es mucho más directo decir:

```
SECRET_KEY = os.getenv('SECRET_KEY', 'dkjewhkrhfkr_secret_key_por_defecto')
```

que es técnicamente lo mismo, ¿cierto?

**Comment by ghost** [comment]
Con el +1 me refería a sobreescribir la clave en producción y no a la forma de
implementarlo. Ambas son equivalentes así que la que más rabia te dé.

Personalmente me inclino más por `os.getenv` para no tener tantos `if`s.

**Comment by astrojuanlu** [comment]
Echad un vistazo al commit a ver qué os parece.

**Comment by niwinz** [comment]
He hecho comentarios inline sobre el diff del commit
