### ISSUE TITLE
Error 500 en vez de 404

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2013#18]
Cada vez que se intenta acceder a un recurso que no existe la aplicación devuelve un error de servidor, en vez de un 404. No estoy seguro de que se trate de Heroku (aunque lo dudo), más bien creo que el problema está en nuestra aplicación. ¿Alguien le puede echar un ojo a esto?

**Comment by niwinz** [comment]
Hay que añadir un template con el nombre 404.html para que no de ese 500.
