### ISSUE TITLE
Fix para el metodo get_article_by_path

### ISSUE THREAD

**Issue by achamorro-dev** [python-spain/PyConES-2013#21]
Después del cambio del campo path a slug toca modificar el método get_article_by_path del manager de Article.

Lo tengo listo para pushear pero para que lo sepáis.

**Comment by yamila-moreno** [comment]
¿Esto sigue abierto? ¿No está para cerrar?

**Comment by achamorro-dev** [comment]
¡Cerrado!

2013/6/3 Yamila notifications@github.com
