### ISSUE TITLE
Closing date of call for papers and calendar

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2013#28]
Nos notifica J. Cea por Twitter

https://twitter.com/jcea/status/341471355247685632

que debería aparecer la fecha de cierre del plazo para enviar las charlas y un calendario para ponentes.

**Comment by astrojuanlu** [comment]
La fecha de cierre podemos añadirla ya, la fecha en la que las ponencias estarán disponibles no la hemos decidido todavía.

**Comment by astrojuanlu** [comment]
Y también habrá que aclarar que son en español:

http://twitter.theinfo.org/341484117269024768#id341486540431704064

**Comment by yamila-moreno** [comment]
Esta tarde puedo hacer el cambio y desplegarlo.

On 3 June 2013 11:42, Juan Luis Cano Rodríguez notifications@github.comwrote:

> Y también habrá que aclarar que son en español:
> 
> http://twitter.theinfo.org/341484117269024768#id341486540431704064
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python-spain/pycones-web/issues/28#issuecomment-18830990
> .

## 

Yamila  Moreno Suárez
http://dendarii.wordpress.com
http://moduslaborandi.net

**Comment by yamila-moreno** [comment]
Subo esta propuesta:

"""
Las charlas se esperan en español o, si es ponente internacional, en inglés. Durarán unos 50 minutos (aprox) y lal final del día habrá una hora para charlas rápidas (5 minutos) que se organizarán en la propia conferencia.
"""
