### ISSUE TITLE
Preinscripción

### ISSUE THREAD

**Issue by ghost** [python-spain/PyConES-2013#32]
@jespino y @yamila-moreno han estado comentando la idea de abrir una preinscripción para hacernos una idea más concreta de la afluencia que podemos esperar.

Abro una issue porque habría que desarrollar una app Django para recoger las preinscripciones (si no existe ya). Lo ideal sería retroalimentarla al proyecto symposion porque puede ser útil para otras conferencias.

**Comment by astrojuanlu** [comment]
¿Se entiende que esa preinscripción se hace sin pagar? En caso afirmativo,
¿nos ffiamos de esos datos? En caso negativo, ¿no ees mejor esperar a
ccerrar el trato con nuestro servicio de venta de entradas y sacar una con
un precio más bajo antes del cierre ddel call for papers?

**Comment by achamorro-dev** [comment]
En un principio la idea de la suscripción a la newsletter surgió además para tener una primera aproximación de personas interesadas en el evento aunque es cierto que no todo el mundo quiere apuntarse a más cosas. Si este numero de suscriptores lo comparamos con los seguidores de twitter podemos tener más o menos una idea del número que barajamos.

Yo por mi parte vería mejor la venta de entradas directamente antes que la preinscripción. Lo veo un trámite intermedio más que imagino debería de tener alguna compensación para el que se apunte.

¿La preinscripción debería llevar ademas un contador de cuantas entradas tienes pensado comprar?

Lo de retroalimentarla al proyecto symposion sería bonito pero todo lo que llevamos hasta ahora creo que ha sido al margen de Symposion :)

**Comment by yamila-moreno** [comment]
¿A qué precio vendemos las entradas cuando aún no tenemos un presupuesto
aproximado? ¿Qué hacemos con el dinero si sobra?

La idea es dimensionar la asistencia para tener margen de maniobra.

¡Un saludo!
Yamila.

2013/6/23 Alberto Chamorro notifications@github.com

> En un principio la idea de la suscripción a la newsletter surgió además
> para tener una primera aproximación de personas interesadas en el evento
> aunque es cierto que no todo el mundo quiere apuntarse a más cosas. Si este
> numero de suscriptores lo comparamos con los seguidores de twitter podemos
> tener más o menos una idea del número que barajamos.
> 
> Yo por mi parte vería mejor la venta de entradas directamente antes que la
> preinscripción. Lo veo un trámite intermedio más que imagino debería de
> tener alguna compensación para el que se apunte.
> 
> ¿La preinscripción debería llevar ademas un contador de cuantas entradas
> tienes pensado comprar?
> 
> Lo de retroalimentarla al proyecto symposion sería bonito pero todo lo que
> llevamos hasta ahora creo que ha sido al margen de Symposion :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python-spain/pycones-web/issues/32#issuecomment-19871274
> .

## 

Yamila  Moreno Suárez
http://dendarii.wordpress.com
http://moduslaborandi.net

**Comment by astrojuanlu** [comment]
On 06/24/2013 08:46 AM, Yamila wrote:

> ¿A qué precio vendemos las entradas cuando aún no tenemos un presupuesto
> aproximado? ¿Qué hacemos con el dinero si sobra?
> 
> La idea es dimensionar la asistencia para tener margen de maniobra.
> 
> ¡Un saludo!
> Yamila.

Creo que si sobra dinero no habría mucho problema: o bien se emplea en 
reforzar la conferencia de este año con cosas que nos hemos dejado en el 
tintero, o se guarda para la del año próximo.

Hablando de dimensionamientos, he añadido una hoja en los presupuestos 
para calcular el coste final por asistente en base a los patrocinadores 
que consigamos. El coste base son unos 50 €, pero teniendo un Diamante y 
dos Platino casi confirmados (a la espera de muchos más) el precio por 
asistente queda en 13 €. Yo creo que si vendemos las entradas tempranas 
a 10 € o incluso 15 € no vamos a tener problemas de dinero.

Un saludo

Juanlu

**Comment by yamila-moreno** [comment]
Es una buena aproximación también, Juanlu. En este caso, podríamos pensar
en poner en marcha la venta de entradas, ¿correcto?

2013/6/24 Juan Luis Cano Rodríguez notifications@github.com

> On 06/24/2013 08:46 AM, Yamila wrote:
> 
> > ¿A qué precio vendemos las entradas cuando aún no tenemos un presupuesto
> > aproximado? ¿Qué hacemos con el dinero si sobra?
> > 
> > La idea es dimensionar la asistencia para tener margen de maniobra.
> > 
> > ¡Un saludo!
> > Yamila.
> 
> Creo que si sobra dinero no habría mucho problema: o bien se emplea en
> reforzar la conferencia de este año con cosas que nos hemos dejado en el
> tintero, o se guarda para la del año próximo.
> 
> Hablando de dimensionamientos, he añadido una hoja en los presupuestos
> para calcular el coste final por asistente en base a los patrocinadores
> que consigamos. El coste base son unos 50 €, pero teniendo un Diamante y
> dos Platino casi confirmados (a la espera de muchos más) el precio por
> asistente queda en 13 €. Yo creo que si vendemos las entradas tempranas
> a 10 € o incluso 15 € no vamos a tener problemas de dinero.
> 
> Un saludo
> 
> Juanlu
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python-spain/pycones-web/issues/32#issuecomment-19892941
> .

## 

Yamila  Moreno Suárez
http://dendarii.wordpress.com
http://moduslaborandi.net

**Comment by astrojuanlu** [comment]
On 06/24/2013 09:58 AM, Yamila wrote:

> Es una buena aproximación también, Juanlu. En este caso, podríamos pensar
> en poner en marcha la venta de entradas, ¿correcto?

Solo queda que elijamos plataforma y restauremos la web en español :)

**Comment by astrojuanlu** [comment]
On 06/24/2013 10:10 AM, Juan Luis Cano wrote:

> On 06/24/2013 09:58 AM, Yamila wrote:
> 
> > Es una buena aproximación también, Juanlu. En este caso, podríamos 
> > pensar
> > en poner en marcha la venta de entradas, ¿correcto?
> 
> Solo queda que elijamos plataforma y restauremos la web en español :)

...y que integremos Acumbamail. A ver si la newsletter de «ya está 
disponible la venta anticipada» puede llegar a todo el mundo sin 
problemas :/

**Comment by yamila-moreno** [comment]
Juanlu, no mezcles hilos que te caneo. La newsletter es independiente de
esto. Y tiene su camino.

La plataforma está elegida (mira el acta de la última reunión).

Sólo queda ponerse a ello. Podemos empezar ya (habrá que probar y tal),
para dar mientras tanto algo de recorrido al despliegue de todos los
idiomas. Que sean mejoras con impacto.

2013/6/24 Juan Luis Cano Rodríguez notifications@github.com

> On 06/24/2013 10:10 AM, Juan Luis Cano wrote:
> 
> > On 06/24/2013 09:58 AM, Yamila wrote:
> > 
> > > Es una buena aproximación también, Juanlu. En este caso, podríamos
> > > pensar
> > > en poner en marcha la venta de entradas, ¿correcto?
> > 
> > Solo queda que elijamos plataforma y restauremos la web en español :)
> 
> ...y que integremos Acumbamail. A ver si la newsletter de «ya está
> disponible la venta anticipada» puede llegar a todo el mundo sin
> problemas :/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python-spain/pycones-web/issues/32#issuecomment-19894034
> .

## 

Yamila  Moreno Suárez
http://dendarii.wordpress.com
http://moduslaborandi.net

**Comment by achamorro-dev** [comment]
Cuidado con juntarnos con la apertura de venta de entradas de la
Codemotion, no nos pisemos y perdamos posibles asistentes :)

Chivatazo: creo que salían a principios de Julio

**Comment by yamila-moreno** [comment]
Buen apunte para tener en mente. Haremos lo posible y lo que mejor encaje.
Cuanto mejor encaje, mejor para todos. Pero no deberíamos organizar este
evento a la sombra de otro. Miremos internamente cuáles son los tempos
necesarios.

2013/6/24 Alberto Chamorro notifications@github.com

> Cuidado con juntarnos con la apertura de venta de entradas de la
> Codemotion, no nos pisemos y perdamos posibles asistentes :)
> 
> Chivatazo: creo que salían a principios de Julio
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python-spain/pycones-web/issues/32#issuecomment-19894480
> .

## 

Yamila  Moreno Suárez
http://dendarii.wordpress.com
http://moduslaborandi.net

**Comment by astrojuanlu** [comment]
On 06/24/2013 10:17 AM, Yamila wrote:

> Juanlu, no mezcles hilos que te caneo. La newsletter es independiente de
> esto. Y tiene su camino.

Zeus me libre de mezclar hilos :P solo estaba diciendo cuáles eran los 
«blockers» en mi opinión.

¿Me encargo yo entonces de hablar con Miguel Araújo de ticketea ya?

**Comment by yamila-moreno** [comment]
Yo abriría la cuestión en la lista, por si alguien tiene algún argumento poderoso a favor o en contra que pueda resultar útil.

**Comment by astrojuanlu** [comment]
Abierto https://lists.es.python.org/pipermail/general/2013-June/001681.html

**Comment by astrojuanlu** [comment]
Al final vamos a usar Ticketea, con lo cual no vamos a programar una aplicación de preinscripción dentro de Symposion. ¿Cerramos la incidencia o la dejamos hasta incluir un enlace a la web de registro?

**Comment by yamila-moreno** [comment]
Conclusión: hemos abierto early bird. 70 entradas. Con ticketea. Cierro la issue.
