### ISSUE TITLE
patrocinadores random

### ISSUE THREAD

**Issue by yamila-moreno** [python-spain/PyConES-2013#36]
Hay que confirmar si los patros están saliendo en orden aleatorio (parece que no)

**Comment by achamorro-dev** [comment]
Yo diría que si. Las pruebas que estuve haciendo ayer me iban cambiando de
posición.

**Comment by yamila-moreno** [comment]
sería mi caché... lo reviso en otros dispositivos.

2013/8/2 Alberto Chamorro notifications@github.com

> Yo diría que si. Las pruebas que estuve haciendo ayer me iban cambiando de
> posición.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/python-spain/pycones-web/issues/36#issuecomment-21986076
> .

## 

Yamila  Moreno Suárez
http://dendarii.wordpress.com
http://moduslaborandi.net

**Comment by sdeancos** [comment]
Por si necesitáis una tercera prueba para cerrar la incidencia, a mi me salen aleatoriamente también :D
